# Dockerfile used to build a build step that builds container-diff in CI.
FROM golang:1.9
RUN apt-get update && apt-get install make && \
    mkdir -p /go/src/github.com/GoogleContainerTools/ && \
    ln -s /workspace /go/src/github.com/GoogleContainerTools/container-diff
WORKDIR /go/src/github.com/GoogleContainerTools/container-diff
